name: macOS Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app

      - name: Install dependencies
        run: sudo xcodebuild -license accept

      - name: Build and analyze
        run: |
          xcodebuild clean build analyze \
            -scheme A2HiresViewer \
            -destination 'platform=macOS' \
            | tee build.log

      - name: Upload build log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
